name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Или ваша основная ветка (master/main)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Обновили до v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Next.js рекомендует Node.js 18+ (лучше 20)

      - name: Install dependencies
        run: npm install

      - name: Build the app (static export)
        run: npm run build  # Next.js создаст папку `out/` (по умолчанию)

      - name: Prepare GitHub Pages
        run: |
          mkdir -p docs
          cp -R out/* docs/.
          echo 'currency-converter-app.example.com' > docs/CNAME  # Если нужно свое доменное имя

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true  # Сохраняет историю деплоев